#!/bin/bash
clear
echo -e "\033[01;31m║\033[0;37m\033[5;34;47m               INICIANDO ATUALIZAÇÃO DO SCRIPT!            \033[0;34m \033[0m\033[01;31m║"
sleep 4s
wget https://raw.githubusercontent.com/MENTALISTA07/SpaceNet-SSH/main/script/install; chmod 777 ./install; ./install

